language: erlang

otp_release:
  - '21.2'

before_script:
  - git clone https://github.com/elixir-lang/elixir.git
  - cd elixir
  - git checkout v1.7.1
  - make test
  - sudo make install
  - cd ..
  - elixir/bin/elixir --version

script:
  - elixir --version
  - ls
  - pwd
  - mix test
